### ISSUE TITLE
Move to NEFSC org

### ISSUE THREAD

**Issue by atyrell3** [NEFSC/NEFSC-Spatial#5]
Move to NEFSC organization per center's github SOP

**Comment by andybeet** [comment]
@atyrell3 @kimberly-bastille At what point do we want to do this? After the next meeting?

**Comment by atyrell3** [comment]
No preference from me. I'm fine with doing it at/after the next meeting.


---

Abby Tyrell, PhD (pronouns: she/her)

Science Analyst, Contractor with Ocean Associates in support of
Ecosystem Dynamics and Assessment Branch

Northeast Fisheries Science Center

NOAA Fisheries |  U.S. Department of Commerce

www.fisheries.noaa.gov

**Comment by kimberly-bastille** [comment]
Same. I think we should transfer it to EDAB first so I can add the issue template. Or it can go directly if you want to do that @andybeet. It just requires admin access.

**Comment by jmhatch** [comment]
Closed #5 as it's completed.
